name: retinanet-gob-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch>=2.7.0
  - torchvision>=0.22
  - torchaudio>=2.7.0
  - torchmetrics>=1.7.1
  - pip:
    - azureml-mlflow>=2.21.3
